### ISSUE TITLE
TW Big Inventory, website offline

### ISSUE THREAD

**Issue by TomRobert** [Vartanov/Tre-Pulsanti#1]
Hey Jackson

Your website casa-olarului.com isn't online anymore and because of that, your script TW Big Inventory isn't working properly anymore.
Can you fix it, or maybe give me author rights on greasyfork for that script?

Greetings Tom Robert (https://greasyfork.org/users/7962-tom-robert)

**Comment by Vartanov** [comment]
> Hey Jackson
> 
> Your website casa-olarului.com isn't online anymore and because of that, your script TW Big Inventory isn't working properly anymore. Can you fix it, or maybe give me author rights on greasyfork for that script?
> 
> Greetings Tom Robert (https://greasyfork.org/users/7962-tom-robert)

Ok, will fix it now! Thx m8!

**Comment by TomRobert** [comment]
Thank you. You forgot to raise the version from 1.5 to 1.6 in the script. Now it says everytime I login to The West, that I have to update.

**Comment by Ruslancic** [comment]
> Thank you. You forgot to raise the version from 1.5 to 1.6 in the script. Now it says everytime I login to The West, that I have to update.

Oh...forgot about that... Will fix it now! Thx

**Comment by Vartanov** [comment]
Fixed!
